---
kind: Service
apiVersion: v1
metadata:
  name: mfl
  labels:
    version: "0.3"
spec:
  selector:
    app: mfl
    version: "0.3"
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfl
  labels:
    name: mfl
    version: "0.3"
spec:
  replicas: 2
  selector:
    matchLabels:
      name: mfl
      version: "0.3"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: mfl
        version: "0.3"
    spec:
      containers:
        - image: bigkaa/mfl:v0.3.2
          name: mfl
          imagePullPolicy: IfNotPresent
          env:
            - name: MFL_CONF_DIR
              value: "/etc/mfl/conf.d"
            - name: MFL_LOG_LEVEL
              value: "debug"
            - name: MFL_BIND_ADDR
              value: "0.0.0.0:8080"
            - name: MFL_CONTEXT
              value: "/mfl"
            - name: MFL_ES_HOST
              value: "http://127.0.0.1"
            - name: MFL_ES_PORT
              value: "9200"
            - name: MFL_ES_USER
              value: "elasticsearch_user"
            - name: MFL_ES_PASSWORD
              value: "elasticsearch_user_password"
            - name: MFL_REDIS_SERVER
              value: "system-redis-master"
            - name: MFL_REDIS_PORT
              value: "6379"
            - name: MFL_REDIS_PASSWORD
              value: "qgh26rvg9it"
            - name: MFL_K8S_POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MFL_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: "0.2"
              memory: "50M"
            limits:
              cpu: "1"
              memory: "200M"
          livenessProbe:
            httpGet:
              path: /mfl/metrics/
              port: 8080
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /mfl/metrics/
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: metrics
              mountPath: /etc/mfl/conf.d/
      restartPolicy: Always
      volumes:
        - name: metrics
          configMap:
            name: metrics
